# Site settings
title: Michal Szulc | techblog
description: "Just another techblog."
url: "http://majkelo.github.io/"
author:
  name: "Michal Szulc"
  email: "majkesz@wp.pl"
  url: "http://majkelo.github.io/"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
gems: [jekyll-paginate]
paginate: 5
paginate_path: /page:num/
#paginate_path: "page:num"

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
